version: '3.1'

networks:
  notes-net:

services:
  db:
    hostname: notesdb
    image: postgres:15
    environment:
      - POSTGRES_USER=notesapi
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=notesapidb
    networks:
      notes-net:
        aliases:
          - notesdb

  api:
    hostname: notesapi
    image: notesapi:latest
    ports:
      - 9080:80
    environment:
      - DB_USERNAME=notesapi
      - DB_PASSWORD=password123
      - DB_NAME=notesapidb
      - DB_HOST=notesdb
      - DB_PORT=5432
    networks:
      notes-net:
        aliases:
          - notesapi

